# Машинное обучение. Практическая работа

В этой практической работе четыре обязательные задачи.

Они помогут понять, что вы действительно усвоили материал модуля. 


Удачи!

## Цели практической работы

Научиться:
- обучать модели, основанные на деревьях решений;
- научиться оценивать и увеличивать их качество.

## Что входит в практическую работу

1. Загрузите датасет и ознакомьтесь с ним.
2. Подготовьте базовую модель дерева решений и измерьте её качество.
3. Подготовьте базовую модель случайного леса и измерьте её качество.
4. Увеличьте точность модели случайного леса на тестовых данных.
5. Проведите анализ влияния признаков на модель.

## Что оценивается

* Выполнены все четыре задачи. Для каждой:
 * в коде нет ручных перечислений, все действия автоматизированы;
 * результаты вычислений и применённых операций корректны;
 * ответы на вопросы, где требуется, корректны и обоснованы; 
 * код читабелен: переменным даны осмысленные названия, соблюдены отступы и правила расстановки пробелов; стилизация кода соответствует рекомендациям [PEP 8](https://pythonworld.ru/osnovy/pep-8-rukovodstvo-po-napisaniyu-koda-na-python.html).

* Репозиторий проекта оформлен корректно:
 * содержит осмысленные коммиты, содержащие конкретные реализованные фичи;
 * ветки названы согласно назначению;
 * файлы, не связанные с проектом, не хранятся в репозитории.


## Как отправить работу на проверку

Сдайте практическую работу этого модуля через систему контроля версий Git сервиса Skillbox GitLab. После загрузки работы на проверку напишите об этом в личном кабинете своему куратору.

## Обязательные задачи

### Описание датасета:
- `id`— идентификатор записи;
- `is_manufacturer_name`— признак производителя автомобиля;

- `region_*`— регион;
- `x0_*`— тип топлива;
- `manufacturer_*`— производитель;
- `short_model_*`— сокращённая модель автомобиля;
- `title_status_*`— статус;
- `transmission_*`— коробка передач;
- `state_*`— штат;
- `age_category_*`— возрастная категория автомобиля;

- `std_scaled_odometer`— количество пройденных миль (после стандартизации);
- `year_std`— год выпуска (после стандартизации);
- `lat_std`— широта (после стандартизации);
- `long_std`— долгота (после стандартизации);
- `odometer/price_std`— отношение стоимости к пробегу автомобиля (после стандартизации);
- `desc_len_std`— количество символов в тексте объявления о продаже (после стандартизации);
- `model_in_desc_std`— количество наименований модели автомобиля в тексте объявления о продаже (после стандартизации);
- `model_len_std`— длина наименования автомобиля (после стандартизации);
- `model_word_count_std`— количество слов в наименовании автомобиля (после стандартизации);
- `month_std`— номер месяца размещения объявления о продаже автомобиля (после стандартизации);
- `dayofweek_std`— день недели размещения объявления о продаже автомобиля (после стандартизации);
- `diff_years_std`— количество лет между годом производства автомобиля и годом размещения объявления о продаже автомобиля (после стандартизации);

- `price`— стоимость;
- `price_category`— категория цены.

1. Подготовка базовой модели

Обучите простую модель классификации с помощью DecisionTreeClassifier на данных из датасета vehicles_dataset_prepared.csv. Для этого сделайте шаги:

1. Обучите модель дерева решений с зафиксированным random_state на тренировочной выборке.
2. Сделайте предикт на тестовой выборке.
3. Замерьте точность на тестовой выборке и выведите матрицу ошибок. 
4. Удалите фичи с нулевыми весами по feature_importance из тренировочной и тестовой выборок.
5. Заново обучите модель и измерьте качество.

In [1]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split 
from sklearn.metrics import accuracy_score, confusion_matrix 

In [2]:
df = pd.read_csv('data/vehicles_dataset_prepared.csv')

df_prepared = df.copy()
df_prepared = df_prepared.drop(['price', 'odometer/price_std'], axis=1)

x = df_prepared.drop(['price_category'], axis=1)
y = df_prepared['price_category']

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.3, random_state=42
)

In [3]:
# Ваш код здесь 
clf = DecisionTreeClassifier()
clf.fit(x_train,y_train)
predicted_train = clf.predict(x_train)
predicted_test = clf.predict(x_test)
print(accuracy_score(y_train, predicted_train))
print(accuracy_score(y_test, predicted_test))
confusion_matrix(y_test,predicted_test)

1.0
0.6677061677061678


array([[735,  51, 211],
       [ 43, 674, 236],
       [198, 220, 518]], dtype=int64)

In [4]:
y_train, predicted_train

(3781      high
 6101      high
 491       high
 3017      high
 3872       low
          ...  
 5734      high
 5191       low
 5390    medium
 860       high
 7270    medium
 Name: price_category, Length: 6733, dtype: object,
 array(['high', 'high', 'high', ..., 'medium', 'high', 'medium'],
       dtype=object))

In [5]:
import matplotlib.pyplot as plt
import numpy as np

In [6]:
clf.feature_importances_

array([0.03491232, 0.00041354, 0.00234369, ..., 0.00253141, 0.01453593,
       0.02399415])

In [7]:
# выводим список значимости всех фичей
f_imp_list = list(zip(x_train.columns, clf.feature_importances_))
f_imp_list.sort(key=lambda x: x[1], reverse=True)
f_imp_list

[('age_category_new', 0.1751319079983745),
 ('std_scaled_odometer', 0.07820011181179917),
 ('model_len_std', 0.07772728831233017),
 ('desc_len_std', 0.07210263341851705),
 ('year_std', 0.0445582949526281),
 ('long_std', 0.04066342471461222),
 ('lat_std', 0.03894018140916605),
 ('id', 0.03491231712557883),
 ('x0_diesel', 0.03351387003418836),
 ('diff_years_std', 0.023994149748299158),
 ('dayofweek_std', 0.014535930088219474),
 ('manufacturer_kia', 0.009912971268583018),
 ('manufacturer_ram', 0.009086927360949458),
 ('short_model_wrangler', 0.00881721860573803),
 ('model_word_count_std', 0.00631780092967697),
 ('short_model_f-150', 0.005957385489242693),
 ('manufacturer_hyundai', 0.005663759938057568),
 ('model_in_desc_std', 0.005511460219761252),
 ('short_model_silverado', 0.005139723845768344),
 ('manufacturer_volkswagen', 0.005093093294519765),
 ('short_model_Scion', 0.004865746378858322),
 ('manufacturer_mercedes-benz', 0.004590363002455255),
 ('manufacturer_gmc', 0.00439309550567793

In [8]:
#убираем все фичи с нулевой значимостью
feats_for_drop = [item for item in f_imp_list if item[1]==0]
feats_for_drop
#конвертируем список из кортежей в список
feats_for_drop = [item[0] for item in feats_for_drop]
feats_for_drop


['short_model_-benz',
 'short_model_1',
 'short_model_124',
 'short_model_128i',
 'short_model_135i',
 'short_model_163869',
 'short_model_1928',
 'short_model_1951',
 'short_model_1954',
 'short_model_1960s',
 'short_model_1968',
 'short_model_1972',
 'short_model_1977',
 'short_model_1978',
 'short_model_198.5',
 'short_model_1988',
 'short_model_1994',
 'short_model_1999',
 'short_model_2',
 'short_model_200',
 'short_model_2000',
 'short_model_2002',
 'short_model_2006',
 'short_model_2007',
 'short_model_2008',
 'short_model_2009',
 'short_model_2012',
 'short_model_2015',
 'short_model_2016',
 'short_model_2017',
 'short_model_2018',
 'short_model_210',
 'short_model_240',
 'short_model_2500hd',
 'short_model_280zx',
 'short_model_3-window',
 'short_model_3.2',
 'short_model_300',
 'short_model_300-series',
 'short_model_300c',
 'short_model_300s',
 'short_model_300zx',
 'short_model_3100',
 'short_model_318i',
 'short_model_320i',
 'short_model_323i',
 'short_model_325ci',
 'sho

In [9]:
df_prepared = df_prepared.drop(columns=feats_for_drop)
x_new = df_prepared.drop(['price_category'], axis=1)
y_new = df_prepared['price_category']

x_train_new,x_test_new,y_train_new,y_test_new=train_test_split(
    x_new,y_new,test_size=0.3,random_state=42
)


In [10]:
df_prepared

id price_category  is_audi  is_ford  is_chevrolet  is_toyota  \
0     7308295377           high        0        0             0          0   
1     7316380095         medium        0        1             0          0   
2     7313733749           high        0        0             0          0   
3     7308210929         medium        0        0             0          1   
4     7303797340         medium        0        0             0          0   
...          ...            ...      ...      ...           ...        ...   
9614  7304876387            low        0        0             0          1   
9615  7316152972         medium        0        0             0          0   
9616  7310993818            low        1        0             0          0   
9617  7306637427           high        0        0             0          0   
9618  7311960763           high        0        0             0          0   

      x0_diesel  x0_electric  x0_gas  x0_hybrid  ...   lat_std  long_std  \
0           1.0          0.0     0.0        0.0  ... -0.619172  0.484245   
1           0.0          0.0     0.0        0.0  ...  0.388014  1.110800   
2           0.0          0.0     1.0        0.0  ... -0.843059  0.531185   
3           0.0          0.0     1.0        0.0  ... -0.504509  0.853562   
4           0.0          0.0     0.0        0.0  ... -0.460101  0.557607   
...         ...          ...     ...        ...  ...       ...       ...   
9614        0.0          0.0     1.0        0.0  ...  0.615626  0.823646   
9615        0.0          0.0     1.0        0.0  ...  0.806702  0.903947   
9616        0.0          0.0     1.0        0.0  ...  1.105428 -1.628875   
9617        0.0          0.0     0.0        1.0  ...  0.773939  0.251959   
9618        0.0          0.0     1.0        0.0  ... -0.337738  0.985465   

      year_std  desc_len_std  model_in_desc_std  model_len_std  \
0     1.322394      0.632075          -0.155788       1.163032   
1     0.695973     -0.646781          -0.155788       0.932087   
2     0.852578      0.560744          -0.155788       0.470197   
3     0.226157      0.180435          -0.155788      -0.915473   
4     0.069552      0.766366          -0.155788       1.163032   
...        ...           ...                ...            ...   
9614 -1.496501     -0.376744          -0.155788      -0.915473   
9615 -0.556869     -0.654060          -0.155788      -0.453583   
9616 -0.087054     -0.668253          -0.155788       1.509450   
9617  0.539367      0.327100          -0.155788      -0.569055   
9618  0.852578      0.632439          -0.155788       1.163032   

      model_word_count_std  month_std  dayofweek_std  diff_years_std  
0                 1.910669  -0.615846       1.120284       -1.322394  
1                 1.235799   1.623784      -1.374972       -0.695973  
2                 0.560930  -0.615846      -0.376870       -0.852578  
3                -0.788810  -0.615846       1.120284       -0.226157  
4                 1.910669  -0.615846       0.122182       -0.069552  
...                    ...        ...            ...             ...  
9614             -0.788810  -0.615846       1.120284        1.496501  
9615             -0.788810   1.623784      -1.374972        0.556869  
9616              1.910669  -0.615846       0.122182        0.087054  
9617             -0.788810  -0.615846      -0.376870       -0.539367  
9618              1.910669  -0.615846       1.120284       -0.852578  

[9619 rows x 377 columns]

In [11]:
clf2 = DecisionTreeClassifier()
clf2.fit(x_train_new, y_train_new)
predicted_train_new = clf2.predict(x_train_new)
predicted_test_new = clf2.predict(x_test_new)
print(accuracy_score(y_train_new, predicted_train_new))
print(accuracy_score(y_test_new, predicted_test_new))
confusion_matrix(y_test_new,predicted_test_new)

1.0
0.6708246708246708


array([[737,  49, 211],
       [ 51, 681, 221],
       [192, 226, 518]], dtype=int64)

2. Подготовка модели случайного леса

Обучите простую модель классификации с помощью RandomForestClassifier. Для этого на новых урезанных семплах тренировочной и тестовой выборок обучите модель случайного леса с зафиксированным random_state=50. 

In [12]:
# Ваш код здесь 
from sklearn.ensemble import RandomForestClassifier
x_train_new2, x_test_new2, y_train_new2, y_test_new2 = train_test_split(
    x_new, y_new, test_size=0.3, random_state=50
)
rf_clf = RandomForestClassifier()
rf_clf.fit(x_train_new2, y_train_new2)

RandomForestClassifier()

2. Сделайте предикт, посчитайте точность модели и матрицу ошибок. Сравните с предыдущей моделью дерева решений. Есть ли случаи, когда модель из пункта 1 отрабатывает лучше, чем модель случайного леса?

Ответ нет таких случаев, у рандомного леса количество истинных определений значений больше чем у 1 модели
а количество неверно определенных меньше чем у 1 модели.

In [13]:
# Ваш код здесь 
predicted_test_rf = rf_clf.predict(x_test_new2)
predicted_train_rf = rf_clf.predict(x_train_new2)
print('train', accuracy_score(y_train_new2, predicted_train_rf))
print('test', accuracy_score(y_test_new2, predicted_test_rf))


train 1.0
test 0.7550242550242551


In [16]:
print('1 model\n',
      confusion_matrix(y_test,predicted_test))
print('random forest\n', 
      confusion_matrix(y_test_new2,predicted_test_rf))

1 model
 [[735  51 211]
 [ 43 674 236]
 [198 220 518]]
random forest
 [[785  35 126]
 [ 12 807 156]
 [159 219 587]]


3. Тюнинг модели случайного леса

Увеличьте точность модели на тестовом датасете RandomForestClassifier c помощью тюнинга параметров. 

Параметры, которые можно настраивать для увеличения точности:
```
    `bootstrap'
    'max_depth'
    'max_features'
    'min_samples_leaf'
    'min_samples_split'
    'random_state'
    'n_estimators'

```

С описанием каждого из параметров можно ознакомиться [в документации](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html).

Задание засчитывается, если значение метрики строго выше 0.76 на тестовом датасете.

In [17]:
rf_clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [ ]:
# Ваш код здесь 
#rf_clf2 = RandomForestClassifier(random_state=50)
#rf_clf2.fit(x_train_new, y_train_new)

In [64]:
param_grid = {
    'n_estimators': list(range(50, 201, 50)),
    'max_features': ['sqrt', 'log2'],
    'min_samples_leaf': list(range(1, 5, 1)),
    #'min_samples_split':list(range(2,10)),
    #'max_depth':list(range(1,5)),
   # 'random_state':list(range(0,42,10)),
   # 'bootstrap':[True,False]
    
}

In [65]:
from sklearn.model_selection import GridSearchCV

# Инициализируем базовую модель
rf_clf2 = RandomForestClassifier(random_state=50)

# Модель для перебора параметров базовой модели
grid_search_rf = GridSearchCV(
    cv=5,
   estimator=rf_clf2,
   param_grid=param_grid,
   scoring='accuracy',
   verbose=2,
   n_jobs=-1
)


In [66]:
# Выполняем перебор параметров
grid_search_rf.fit(x_train_new2, y_train_new2)

# Выводим лучшие параметры
best_params = grid_search_rf.best_params_
print(best_params)
#Fitting 5 folds for each of 20 candidates, totalling 100 fits
#{'n_estimators': 400, 'min_samples_leaf': 1, 'max_features': 'log2'}

Fitting 5 folds for each of 32 candidates, totalling 160 fits
{'max_features': 'log2', 'min_samples_leaf': 1, 'n_estimators': 150}


In [63]:
rf_tuned = RandomForestClassifier(
    random_state=None,
    max_features='sqrt',
    min_samples_leaf=1, 
    n_estimators=150,
    min_samples_split=2,
    max_depth=None,
    bootstrap=True
)

rf_tuned.fit(x_train_new2, y_train_new2)


tuned_preds_rf = rf_tuned.predict(x_test_new2)
accuracy_score(y_test_new2, tuned_preds_rf)

print((f'Tuned RF Model Accuracy: {accuracy_score(y_test_new2, tuned_preds_rf):.5f}'))


#{'bootstrap': True,
# 'ccp_alpha': 0.0,
# 'class_weight': None,
# 'criterion': 'gini',
 #'max_depth': None,
# 'max_features': 'sqrt',
# 'max_leaf_nodes': None,
# 'max_samples': None,
# 'min_impurity_decrease': 0.0,
# 'min_samples_leaf': 1,
# 'min_samples_split': 2,
# 'min_weight_fraction_leaf': 0.0,
# 'n_estimators': 100,
# 'n_jobs': None,
# 'oob_score': False,
# 'random_state': None,
# 'verbose': 0,
 #'warm_start': False}

Tuned RF Model Accuracy: 0.76057


In [67]:
from sklearn.model_selection import cross_validate

4. Анализ влияния фичей на модель

До этого в задачах вы работали над подготовленным датасетом, где фичи были заранее извлечены из текстовых переменных, отскейлены и пропущены через OneHotEncoder. Сравним, какой была бы предсказательная способность модели, если бы мы использовали только сырые данные из исходного датасета. Для этого проделайте следующие шаги:

1. Загрузите датасет `vehicles_dataset_old.csv`.
2. Удалите из него переменную `price` и все строковые колонки. Дерево решений и случайный лес не умеют самостоятельно работать со строковыми значениями.
3. Сформируйте x_train и x_test так же, как они были сформированы в предыдущих заданиях.
4. Обучите свою лучшую модель случайного леса на новых данных и замерьте качество. Убедитесь, что оно ухудшилось.
5. Найдите три фичи, которые лучшим образом повлияли на предсказательную способность модели.

In [68]:
df_old = pd.read_csv('data/vehicles_dataset_old.csv')
df_old.head()

id                                                url  \
0  7308295377  https://chattanooga.craigslist.org/ctd/d/chatt...   
1  7316380095  https://newjersey.craigslist.org/ctd/d/carlsta...   
2  7313733749  https://reno.craigslist.org/ctd/d/atlanta-2017...   
3  7308210929  https://fayetteville.craigslist.org/ctd/d/rale...   
4  7303797340  https://knoxville.craigslist.org/ctd/d/knoxvil...   

         region                           region_url  price  year  \
0   chattanooga   https://chattanooga.craigslist.org  54990  2020   
1  north jersey     https://newjersey.craigslist.org  16942  2016   
2  reno / tahoe          https://reno.craigslist.org  35590  2017   
3  fayetteville  https://fayetteville.craigslist.org  14500  2013   
4     knoxville     https://knoxville.craigslist.org  14590  2012   

  manufacturer                   model    fuel  odometer title_status  \
0          ram  2500 crew cab big horn  diesel     27442        clean   
1         ford    explorer 4wd 4dr xlt   other     60023        clean   
2   volkswagen        golf r hatchback     gas     14048        clean   
3       toyota                    rav4     gas    117291        clean   
4          bmw  1 series 128i coupe 2d   other     80465        clean   

  transmission                                          image_url  \
0        other  https://images.craigslist.org/00N0N_1xMPvfxRAI...   
1    automatic  https://images.craigslist.org/00x0x_26jl9F0cnL...   
2        other  https://images.craigslist.org/00y0y_eeZjWeiSfb...   
3    automatic  https://images.craigslist.org/00606_iGe5iXidib...   
4        other  https://images.craigslist.org/00F0F_5UAXmOzC18...   

                                         description state        lat  \
0  Carvana is the safer way to buy a car During t...    tn  35.060000   
1  ***Call Us for more information at: 201-635-14...    nj  40.821805   
2  Carvana is the safer way to buy a car During t...    ca  33.779214   
3  2013 Toyota RAV4 XLE 4dr SUV     Offered by: R...    nc  35.715954   
4  Carvana is the safer way to buy a car During t...    tn  35.970000   

        long              posting_date price_category  \
0 -85.250000  2021-04-17T12:30:50-0400           high   
1 -74.061962  2021-05-03T15:40:21-0400         medium   
2 -84.411811  2021-04-28T03:52:20-0700           high   
3 -78.655304  2021-04-17T10:08:57-0400         medium   
4 -83.940000  2021-04-08T15:10:56-0400         medium   

                        date  
0  2021-04-17 16:30:50+00:00  
1  2021-05-03 19:40:21+00:00  
2  2021-04-28 10:52:20+00:00  
3  2021-04-17 14:08:57+00:00  
4  2021-04-08 19:10:56+00:00

In [83]:
columns_for_drop = []
for column in df_old.columns:
    if type(df_old.loc[0,column])==str:
        columns_for_drop.append(column)
columns_for_drop = columns_for_drop[0:12]+columns_for_drop[13:]
columns_for_drop
    

['url',
 'region',
 'region_url',
 'manufacturer',
 'model',
 'fuel',
 'title_status',
 'transmission',
 'image_url',
 'description',
 'state',
 'posting_date',
 'date']

In [85]:
# Ваш код здесь 
df_old_drop = df_old.drop(['price'], axis=1)
df_old_drop = df_old_drop.drop(columns=columns_for_drop)
df_old_drop

id  year  odometer        lat        long price_category
0     7308295377  2020     27442  35.060000  -85.250000           high
1     7316380095  2016     60023  40.821805  -74.061962         medium
2     7313733749  2017     14048  33.779214  -84.411811           high
3     7308210929  2013    117291  35.715954  -78.655304         medium
4     7303797340  2012     80465  35.970000  -83.940000         medium
...          ...   ...       ...        ...         ...            ...
9614  7304876387  2002    150000  42.123900  -79.189500            low
9615  7316152972  2008    113573  43.216990  -77.755610         medium
9616  7310993818  2011    150184  44.925908 -122.982753            low
9617  7306637427  2015     61943  43.029559  -89.397796           high
9618  7311960763  2017     35921  36.670000  -76.300000           high

[9619 rows x 6 columns]

In [86]:
x_old = df_old_drop.drop(['price_category'], axis=1)
y_old = df_old['price_category']

x_train_old,x_test_old,y_train_old,y_test_old=train_test_split(
    x_old,y_old,test_size=0.3,random_state=42
)

In [114]:
rf_tuned = RandomForestClassifier(
    random_state=None,
    max_features='sqrt',
    min_samples_leaf=1, 
    n_estimators=150,
    min_samples_split=2,
    max_depth=None,
    bootstrap=True
)
rf_tuned.fit(x_train_old, y_train_old)

RandomForestClassifier(n_estimators=150)

In [115]:
predicted_test_rf_old = rf_tuned.predict(x_test_old)
predicted_train_rf_old = rf_tuned.predict(x_train_old)
print('train', accuracy_score(y_train_old, predicted_train_rf_old))
print('test', accuracy_score(y_test_old, predicted_test_rf_old))

train 1.0
test 0.6330561330561331


In [119]:
print('test prepared data\n',
      confusion_matrix(y_test_new2, tuned_preds_rf),
      accuracy_score(y_test_new2, tuned_preds_rf))
print('test old data\n',
      confusion_matrix(y_test_old,predicted_test_rf_old),
      accuracy_score(y_test_old, predicted_test_rf_old))

test prepared data
 [[789  40 117]
 [ 13 811 151]
 [155 215 595]] 0.7605682605682605
test old data
 [[705  76 216]
 [ 46 711 196]
 [281 244 411]] 0.6330561330561331


In [123]:
f_imp_list_old = list(zip(x_train_old.columns, rf_tuned.feature_importances_))
f_imp_list_old.sort(key=lambda x: x[1], reverse=True)
print(f_imp_list_old[:3])

[('odometer', 0.2655632920002698), ('year', 0.2364019637562666), ('id', 0.16802278044163557)]
